### ISSUE TITLE
new features in shortcut?

### ISSUE THREAD

**Issue by ghost** [rchrd2/shortcut#3]
Hi everyone.

*I'd like to contribute a series of visual changes to the shortcut repository. My idea would be to add the name add, instead of shortcut.*

#### *before*
![image](https://user-images.githubusercontent.com/111701513/208267548-eae1e6f3-367f-4113-ad03-b914d4a4624b.png)

#### *after*
![image](https://user-images.githubusercontent.com/111701513/208267528-be83fed3-00b0-4dc9-abba-79c54ec8edc9.png)

#### Read-design *new README.md*
![image](https://user-images.githubusercontent.com/111701513/208267741-daffc7a8-bd22-4194-95b9-68c075d6fb01.png)

#### Choose where your commands will be stored
- Choose Google drive or Dropbox to store command history information or shortcuts.
- Another option is to store the commands in orbit-db, ipfs, ftp or remote-storage

**Comment by rchrd2** [comment]
Hi These are cool ideas, but I am no longer working on this tool. I've switched to using more bash aliases in my workflow. Feel free to fork this and link back to this repo as reference.

**Comment by ghost** [comment]
Hi rchrd2.

> Hi These are cool ideas, but I am no longer working on this tool. I've switched to using more bash aliases in my workflow. 

thank you for feedback.

> Feel free to fork this and link back to this repo as reference.

I added your credits in this url: `https://github.com/public-source-archive/add`

*anyway, thank you for feedback again.*
